### ISSUE TITLE
Fix `html_url` of a model instance of a GitHub model

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/model-backend#125]
For a model imported from GitHub, currently, the `html_url` of a model instance is the same as the `html_url` of the model.

See the example below.

```bash
{
    "instances": [
        {
            "name": "models/mobilenetv2/instances/v1.0-gpu",
            "uid": "eed7a7ad-fdd3-4d3a-bb45-857cf0ddb553",
            "id": "v1.0-gpu",
            "state": "STATE_OFFLINE",
            "task": "TASK_CLASSIFICATION",
            "model_definition": "model-definitions/github",
            "configuration": "{\"tag\": \"v1.0-gpu\", \"html_url\": \"https://github.com/instill-ai/model-mobilenetv2\", \"repository\": \"instill-ai/model-mobilenetv2\"}",
            "create_time": "2022-06-21T16:59:35.119723Z",
            "update_time": "2022-06-21T16:59:35.119723Z"
        }
        ...
    ],
    "next_page_token": "",
    "total_size": "3"
}
```

But according to the [JSON schema](https://github.com/instill-ai/model-backend/blob/cc0388907df940b28c2ee89f5e6cc8ac1978732b/config/init/instill/seed/model_definitions.yaml#L69), the `html_url` of a model instance should be with the format
`{model's html_url}/tree/{release_tag}`. 

Use the above as an example, the refactored model instance `html_url` should be `https://github.com/instill-ai/model-mobilenetv2\tree\v1.0-gpu`.

**Comment by Phelan164** [comment]
fixed in #128
