### ISSUE TITLE
Container command is inconsistent

### ISSUE THREAD

**Issue by pinglin** [instill-ai/model-backend#20]
`model-backend` has a docker command "./openapi" at the moment. 

It should be `model-backend` to cohere other backends.

**Comment by Phelan164** [comment]
@pinglin yes I agree. But currently have source dir named `model-backend` in container, so I will name docker command `model`.

**Comment by Phelan164** [comment]
@pinglin Yes, I agree. But there is working dir named `model-backend` store some stuff such as ssl, so I will rename it to docker compose to `model`
