### ISSUE TITLE
Wrong model type

### ISSUE THREAD

**Issue by pinglin** [instill-ai/model-backend#22]
The model type is mistakenly set as `tensorrt`.
https://github.com/instill-ai/model-backend/blob/9eb75d70b00198b6a0362e294104d07a082f7ba4/examples-go/grpc_client.go#L65

**Comment by Phelan164** [comment]
@pinglin `examples-go/grpc_client.go` is quickstart script for model-backend and I think that we should keep one in model-backend.

**Comment by Phelan164** [comment]
@pinglin for current model type, I make it to optional and remove it from examples
