### ISSUE TITLE
Remove unimplemented functions

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/model-backend#26]
This function is not handled by the backend. We should remove it from the protobuf to avoid confusion. 

https://github.com/instill-ai/model-backend/blob/7d799b7e0936099907a5b12128d3df6183b73fd0/rpc/model.go#L518-L521

**Comment by Phelan164** [comment]
@xiaofei-du this method used for base64/url prediction. I will add the implementation later

**Comment by xiaofei-du** [comment]
Then, this issue is linked to #27.​
