### ISSUE TITLE
Support multiple image inference for multipart form upload

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/model-backend#47]

**Comment by Phelan164** [comment]
@xiaofei-du  I think it is already supported. 
I tested with multiple images inference as below
<img width="669" alt="image" src="https://user-images.githubusercontent.com/2509508/159949708-41cd375b-4686-4c09-80b9-21c9af3f5842.png">
The response:
```
{
    "output": {
        "detection_outputs": [
            {
                "bounding_box_objects": [
                    {
                        "bounding_box": {
                            "height": 402.58002,
                            "left": 325.79257,
                            "top": 99.084984,
                            "width": 204.18991
                        },
                        "category": "dog",
                        "score": 0.980409
                    },
                    {
                        "bounding_box": {
                            "height": 242.36629,
                            "left": 133.76927,
                            "top": 195.17857,
                            "width": 207.40648
                        },
                        "category": "dog",
                        "score": 0.90092707
                    }
                ]
            },
            {
                "bounding_box_objects": [
                    {
                        "bounding_box": {
                            "height": 2348.3347,
                            "left": 156.61142,
                            "top": 38.865856,
                            "width": 3173.3892
                        },
                        "category": "cup",
                        "score": 0.9963998
                    }
                ]
            }
        ]
    }
}
```

**Comment by pinglin** [comment]
In gRPC [TriggerModelBinaryFileUpload](https://github.com/instill-ai/model-backend/blob/v0.3.2-alpha/rpc/model.go#L562) method, the protobuf name is [bytes](https://github.com/instill-ai/protobufs/blob/v0.1.5-alpha/instill/model/v1alpha/model.proto#L234). However, in the gRPC-Gateway custom handler, the form data each is named [inputs](https://github.com/instill-ai/model-backend/blob/v0.3.2-alpha/rpc/payload.go#L133). 

On one hand, I think we'd better just consistently name them `bytes`. On the other hand, I think the gRPC-Gateway custom handler function should simply use `protogen-go` struct to use the `bytes` variable directly. In this way, we don't deviate variables in the custom function from the protobuf definition, but rather bundle gRPC and REST handler function strictly.

**Comment by Phelan164** [comment]
@pinglin for naming consitency, I think it also consistent with other API method `[TriggerModel](https://github.com/instill-ai/protobufs/blob/main/instill/model/v1alpha/model.proto#L252)`

**Comment by xiaofei-du** [comment]
After discussion, I think we can use different field names for multipart binary upload and gRPC binary upload.

We can 
- rename the multipart binary upload from `inputs` to `file`
- remove `byte` and only use `file_bytes` for gPRC (the field is a list of uploaded file sizes) 

@pinglin and @Phelan164, What do you think?
