### ISSUE TITLE
Adopt koanf for configuration

### ISSUE THREAD

**Issue by pinglin** [instill-ai/model-backend#54]

**Comment by Phelan164** [comment]
@pinglin what is the main reason for adopting koanf?
I found that koanf support more type of configuration
configor  support `YAML, JSON, TOML, Shell Environment`
koanf support more `JSON, TOML, YAML, env, command line, file, S3 etc`

**Comment by pinglin** [comment]
> @pinglin what is the main reason for adopting koanf? I found that koanf support more type of configuration [configor](https://github.com/jinzhu/configor) support `YAML, JSON, TOML, Shell Environment` [koanf](https://github.com/knadh/koanf) support more `JSON, TOML, YAML, env, command line, file, S3 etc`

It was just a consensus we've reached long time ago.

**Comment by Phelan164** [comment]
Okie, I got it
