### ISSUE TITLE
Check if the imported GitHub repo is duplicated

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/model-backend#59]
When a user imports a GitHub model repo, the backend will check if the repo has been already imported and deployed to avoid duplication.

**Comment by Phelan164** [comment]
@xiaofei-du currently, model-backend will auto-increase version. So if same repo is imported and deployed, model-backend will create a new version and deployed the version. So there is no duplication. What do you think about this flow?

**Comment by xiaofei-du** [comment]
> @xiaofei-du currently, model-backend will auto-increase version. So if same repo is imported and deployed, `model-backend` will create a new version and deployed the version. So there is no duplication. What do you think about this flow?

For now, yes. Let's check duplication when we support real-time sync from GitHub repo.
