### ISSUE TITLE
Return resource name for the `user` field in the model

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/model-backend#88]
Based on the model [proto](https://github.com/instill-ai/protobufs/blob/5e522613bb8ce230e465c1a6d01b1905f3c7de31/instill/model/v1alpha/model.proto#L58-L59), the `user` field should be the resource name, e.g., `users/local-user`, not the permalink `users/{uid}`.

**Comment by Phelan164** [comment]
@xiaofei-du it fixed and committed into main branch
